import { Button } from '@mui/material';
import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Homework Scheduler</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Homework Scheduler</h1>
				<Button variant="contained">Hello World</Button>
			</main>
		</div>
	);
}
